language: node_js
# 指定需要sudo权限
# sudo: required
node_js: 
  - 14
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public
  repo: furrybear/furrybear.github.io
  target_branch: master
  on:
    branch: src
